### ISSUE TITLE
Plug.MIME.type/1 is deprecated

### ISSUE THREAD

**Issue by scottmessinger** [pryin-io/pryin#15]
I'm seeing the following errors throughout my logs when I'm using Pryin.

```
backend  │ Plug.MIME.type/1 is deprecated, please use MIME.type/1 instead
backend  │     (phoenix) lib/phoenix/controller.ex:636: Phoenix.Controller.do_render/4
backend  │     (my_app) web/controllers/card_stack_controller.ex:1: Spikey.CardStackController.action/2
backend  │     (my_app) web/controllers/card_stack_controller.ex:1: Spikey.CardStackController.phoenix_controller_pipeline/2
backend  │     (my_app) lib/my_app/endpoint.ex:1: Spikey.Endpoint.instrument/4
backend  │     (my_app) lib/phoenix/router.ex:261: Spikey.Router.dispatch/2
backend  │     (my_app) web/router.ex:1: Spikey.Router.do_call/2
backend  │     (my_app) lib/plug/error_handler.ex:64: Spikey.Router.call/2
backend  │     (my_app) lib/my_app/endpoint.ex:1: Spikey.Endpoint.phoenix_pipeline/1
backend  │     (my_app) lib/my_app/endpoint.ex:3: Spikey.Endpoint."call (overridable 2)"/2
backend  │     (my_app) lib/my_app/endpoint.ex:3: Spikey.Endpoint."call (overridable 3)"/2
backend  │     (my_app) lib/plug/debugger.ex:99: Spikey.Endpoint."call (overridable 4)"/2
backend  │     (my_app) lib/my_app/endpoint.ex:1: Spikey.Endpoint.call/2
backend  │     (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
backend  │     (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by manukall** [comment]
hi @scottmessinger, thanks for the bug report.
we got those warnings in another project, too. i think they are not related to pryin, though, but appear when using the most recent version of plug with phoenix < 1.3.
see https://github.com/phoenixframework/phoenix/issues/2400, too.
